<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SystemIQ.Application\SystemIQ.Application.csproj" />
    <ProjectReference Include="..\SystemIQ.Domain\SystemIQ.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.8" />
    <PackageReference Include="MySqlConnector" Version="2.4.0" />
    <PackageReference Include="SqlParserCS" Version="0.6.5" />
  </ItemGroup>
</Project>
